### ISSUE TITLE
Use camelCase when naming functions and variables

### ISSUE THREAD

**Issue by MartinSvarrer** [Sitecore-Community/Sitecore.Speak.Guidance#19]
In the new Core we now have PascalCase for the properties defined by the server. We should agree on being consistent. If it is a big deal for us to have PascalProperties so they match the properties in C# code style - I think we should consider adapting the C# coding styles for naming.

**Comment by dervalp** [comment]
Sorry but I am not sure I understand your comment :).

Do you say: "we should use PascalProperties in Javascript" to match the C#.

If yes, this is how it is done fore CORE 1.2 as the Properties are generated based on the Model in Razor (where the properties are PascalCase).

**Comment by MartinSvarrer** [comment]
I am saying we now are using Pascal for properties in the new core.
But the guidance states we should use camelCase. And if anybody is going to create a property in JS today they would probably do it with camelCase. I think we should start consistently to use Pascal.

**Comment by dervalp** [comment]
:+1: I agree

**Comment by MaxReimerNielsen** [comment]
What about methods, internal variables etc? Do we use the C# standard, or go all PascalCase everywhere, or is it up to people themselves to decide?

1.
function Something() {
 var SomethingElse;
}

2.
function something() {
 var somethingElse;
}

3.
function Something() {
 var somethingElse;
}

In C# to my knowledge they use camelCase for internals while PascalCase is for public. Do we have this distinction in SPEAK 2.0? I mean can we somehow create internal methods?

Personally I think properties in PascalCase is nice, since they already are that in SCR, C# etc.

**Comment by MartinSvarrer** [comment]
I think max has a good point here. I suggest:
- PascalCase for public methods and properties
- camelCase for local vars, parameters and local functions

One thing we should consider though. What are the best practices for writing methods not exposed. Say we want to handle a click event or do some calculations. Our API for the component should not expose a ClickHandler method. People will try to use them and ~~fail~~ depend on them.

**Comment by MartinSvarrer** [comment]
This suggestion will give us a component in JS looking a little like this:

```
Speak.component(["utils/name"], function(nameUtil) {
  return {
    initialize: function() {
      this.defineComputedProperty("Title", this.GetTitle);
      this.defineProperty("FirstName", "");
      this.defineProperty("LastName", "");
    },

    initialized: function() {
    },

    GetTitle: function() {
      return nameUtil.IsMale(this.FirstName) ? nameUtil.TITLE_MR : nameUtil.TITLE_MRS;
    }
  };
}, "Person");
```

**Comment by dervalp** [comment]
Then we need to change the case in the CORE to be consistent.

Initialize
Initialized
Render

The problem with naming a function in PascalCase is that generally PascalCase are using for namespace. But you could say the same for Properties.

The problem is I think it is be better to be consistent isomorphicaly (server/client) but that breaks the JavaScript convention that JS Devs has.

It is tricky, For sure, the C# guys will never accept to have camelCase in their public properties/methods. So I guess we need to switch to PascalCase in JS.

**Comment by MaxReimerNielsen** [comment]
If there wasn't a breaking change before, there defiantly is after this :)

But I also very much approve it :+1:

All or nothing!

**Comment by dervalp** [comment]
It is not a breaking change because BCL2 are new components. I would change it only in the CORE 2.0. So at least with SPEAK 2.0, we would start clean.

**Comment by MaxReimerNielsen** [comment]
What about JSON formatting? Will these rules also apply here - if it will be decided to go all PascalCase?

**Comment by dervalp** [comment]
Stop asking question :) 

Good point but I do not think we should switch JSON notation. I would keep JSON notation as it is.

**Comment by MartinSvarrer** [comment]
haha.. So JSON is for Speak 3.0 :P 
I am not so sure anymore it is worth changing JS style conventions for PascalCase, because the properties are defined in C#. I think I like the old approach better - where we change the properties to camelCase.

**Comment by dervalp** [comment]
hehe :) that's tricky isn't it? I am not sure there is a perfect solution.

**Comment by MaxReimerNielsen** [comment]
I actually still find it "attractive" that we do PascalCasing for properties from C#, because it will be a fast way for the developer to see that:

this.doSomething() // method created by JavaScript
this.Something // created by the component it self
this.someOtherThing // variable created by JavaScript

So I still think we should keep PascalCasing on the properties, and then just skip (use standard JavaScript casing) it everywhere else.

**Comment by dervalp** [comment]
that was the original idea.

**Comment by MartinSvarrer** [comment]
Okay Lets just stick to that :) I'll close this issue then.
