### ISSUE TITLE
Create all other pages accessible from the Dashboard page as sub-items under the Dashboard page

### ISSUE THREAD

**Issue by ivan-korshun** [Sitecore-Community/Sitecore.Speak.Guidance#7]
The following is written in [ApplicationDefinitionStorage.md](https://github.com/Sitecore-Community/Sitecore.Speak.Guidance/blob/gh-pages/Application%20Development/General%20Guidelines/ApplicationDefinitionStorage.md):

> Create all other pages accessible from the Dashboard page as sub-items under the Dashboard page.

Imagine that I am creating EXM application.
I have the Dashboard page, where I can select a message. Also I have Message task page, where message details are shown.
According to this rule, the URL path will be “…/applications/EXM/Dashboard/Message”.
But this URL looks logically wrong to me because Message is not related to Dashboard ( correct one is “…/applications/EXM/Message”).
In addition, such an approach increases length of related file paths (for example, page code files).

**Comment by dervalp** [comment]
We have created this that way in order to have the breadcrumbs working out of the box. You would point your breacrumb data source to the Dashboard and it would be automatically generated.

Define that kind structure would help us later to auto-generate some components. It is important to keep a rigid structure with the Dashboard as a Root Page.

If I follow what you are saying, we should create EXM as the Dashboard page and not as a folder. Like this the url would not have Dashboard in it and we would keep the Dashboard page as the root of the application. it would be /applications/EXM/Message.

**Comment by kerrybellerose** [comment]
I think the important phrase in the guidance is "pages accessible from the Dashboard".  As Pierre says, following this guideline allows the breadcrumb to function properly.  

I expect that this will work appropriately with the Menu component as well, although I'd be interested in knowing if this guidance may contradict appropriate usage of the Menu component.

If, on the other hand, the Message task page is not directly accessible from the Dashboard, then I would expect developers would not place it as an immediate sub-item of the Dashboard.

**Comment by ivan-korshun** [comment]
> we should create EXM as the Dashboard page and not as a folder. Like this the url would not have Dashboard in it and we would keep the Dashboard page as the root of the application. it would be /applications/EXM/Message.

I like this idea of relacing an aplication folder item with Dashboard item.
It would be good to mention this possibility in our guidance.

**Comment by kerrybellerose** [comment]
I suppose that some applications may be small enough that they don't need an application folder.  

On the other hand, not every page will necessarily be directly accessible from the Dashboard, and there are often good reasons to have folders on the same level as the Dashboard which contain application wide configuration items.  

This discussion, however, suggests that perhaps we should explain why we recommend making pages accessible to the Dashboard as sub-pages (so that the breadcrumb can work automatically).

How about this:

> Create all other pages accessible from the Dashboard page as sub-items under the Dashboard page, so that the navigation components, such as the Breadcrumb, can generate an appropriate structure.

Pierre, do you think this is accurate?

**Comment by dervalp** [comment]
it is accurate.

**Comment by kerrybellerose** [comment]
Fixed.
